### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by xiaobinboy** [bjvolcano/encryptClass#1]
Unable to register to the spring ioc container ,can you help me,author!
the autowird annoation in myComponent dont  take effect.
i have use this encrypt plugin to  run the command  named encrypt :encrypt ,can it can generate encrypted file ,why?
 
![e03110c70959b6b633e0fa63ff9f03c](https://user-images.githubusercontent.com/63184821/147454830-afc476c5-ceb7-4a03-a60d-b56ef7a42998.png)

**Comment by bjvolcano** [comment]
sorry，maven dependency error，I have fixed it.
please pull code ,retry.

**Comment by bjvolcano** [comment]
please 

> mvn npackage

 first ,Then run the test.

![image](https://user-images.githubusercontent.com/5397891/147800613-dec135c9-fab6-4e3a-abb4-3ac10d9dd451.png)


encrypted  project。 please Reference 

> encrypted/pom.xml

use encrypted  project dependency,please Reference

> test/pom.xml
